manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: black-trooper
      url-base: https://github.com/black-trooper
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      revision: main
    - name: zmk-input-processor-xyz
      remote: badjeff
      revision: main
    - name: zmk-driver-paw3222
      remote: black-trooper
      revision: main
  self:
    path: config
